package com.backendorg.quizapp.domain;

public enum Category {
    JAVA,
    SPRING,
    ANDROID,
    IOS,
    NODE_JS,
    PYTHON,
    ML,
    DATA_STRUCTURE,
    SOFTWARE_ARCHITECTURE,
    SOFTWARE_DEVELOPMENT,
    DATABASE_MANAGEMENT,
    ALGORITHMS,
    CONCURRENT_PROGRAMMING,
    VERSION_CONTROL,
    PROGRAMMING_LANGUAGES,
    FUNCTIONAL_PROGRAMMING,
    OBJECT_ORIENTED_PROGRAMMING,
    MACHINE_LEARNING,
    ;
}
